
pub fn try_get_name(id: u16) -> Option<&'static str> {
	VENDORS.binary_search_by_key(&id, |(id, _)| *id)
		.map(|idx| VENDORS[idx].1)
		.ok()
}

pub fn get_name(id: u16) -> &'static str {
	try_get_name(id)
		.unwrap_or(VENDOR_UNKNOWN)
}

static VENDOR_UNKNOWN: &str = "UNKNOWN VENDOR";

static VENDORS: [(u16, &str); 978] = [
	(0x0014, "Loongson Technology Corporation Limited"),
	(0x001C, "PEAK-System Technik GmbH"),
	(0x00B0, "Blue Origin, LLC"),
	(0x00BB, "Bloombase"),
	(0x0123, "General Dynamics Mission Systems, Inc."),
	(0x012E, "OLZETEK"),
	(0x01B8, "Sintela Ltd"),
	(0x0222, "Not for Radio, LLC"),
	(0x0303, "DAQ System"),
	(0x2782, "Emdoor Digital Technology Co., Ltd"),
	(0x27D1, "Angelbird Technologies GmbH"),
	(0x0488, "Cirque Corporation"),
	(0x301F, "WOLF Advanced Technology"),
	(0x04DB, "CLEVER INFORMATION INC."),
	(0x3100, "Dynabook Inc."),
	(0x3264, "RnD Center \"ELVEES\", JSC"),
	(0x0526, "Unicompute Technology Co., Ltd."),
	(0x3442, "Bihl + Wiedemann GmbH"),
	(0x3475, "Arista Networks, Inc."),
	(0x3842, "EVGA Corporation"),
	(0x38EF, "4Links Limited"),
	(0x060E, "Lightelligence, Inc."),
	(0x3DEE, "SunRise Memory Corp."),
	(0x4144, "Alpha Data Parallel Systems Ltd."),
	(0x4149, "AIMOTIVE Kft."),
	(0x4153, "Active Silicon, Ltd."),
	(0x434E, "Cornelis Networks, Inc."),
	(0x4453, "dSPACE GmbH"),
	(0x4547, "Salland Engineering (Europe) b.v"),
	(0x0731, "Changsha Jingjia Microelectronics Co., Ltd."),
	(0x4C54, "Nanjing Lisuan Technology Co., Ltd."),
	(0x4D54, "Microtechnica Co., Ltd."),
	(0x4D56, "Matrix Vision GmbH"),
	(0x1BEE, "HMS Technology Center Ravensburg GmbH"),
	(0x1C24, "Elma Electronic Inc"),
	(0x4E58, "Nutanix, Inc."),
	(0x4EEB, "Nebulon Inc"),
	(0x0800, "Hirota Seisakusho Limited"),
	(0x50C1, "Socionext Inc."),
	(0x0823, "Hangzhou Hongjun Microelectronics Co., Ltd."),
	(0x5353, "iodyne"),
	(0x5554, "Applied Research Laboratories, The University of Texas at Austin"),
	(0x5658, "VX Instruments GmbH"),
	(0x5743, "WALTON DIGI-TECH INDUSTRIES LIMITED"),
	(0x5845, "Extreme Engineering Solutions"),
	(0x5853, "Citrix Systems UK Ltd"),
	(0x5942, "Yellowbrick Data"),
	(0x5959, "Jiangsu Yunyong Electronics and Technology Co., Ltd."),
	(0x0909, "Intelligence Draw Microelectronics(Nanjing) Co., Ltd."),
	(0x6766, "Glenfly Tech Co., Ltd."),
	(0x6899, "ZT Systems"),
	(0x0A7C, "Aurora Innovation Opco, Inc."),
	(0x6D5E, "Guntermann & Drunck GmbH"),
	(0x7053, "Synology Inc."),
	(0x7377, "Shenzhen Colorful Yugong Technology and Development Co., Ltd."),
	(0x0BAE, "Bachmann electronic GmbH"),
	(0x7548, "INUITIVE LTD."),
	(0x78C0, "Herrick Technology Laboratories (HTL), Inc."),
	(0x0CCD, "Preferred Networks, Inc."),
	(0x8009, "Shengli Technologies Co., Ltd"),
	(0x8080, "StoreSwift Technology Co., Ltd."),
	(0x8086, "Intel Corporation"),
	(0x8088, "Beijing Wangxun Technology Co., Ltd."),
	(0x8510, "Xi'an Sietium Semicoductor CO., LTD"),
	(0x8686, "SAP SE"),
	(0x9000, "C-Core Technology Co., Ltd."),
	(0x9588, "Beijing JCZ Technology Co., Ltd"),
	(0x9753, "PEZY Computing K.K."),
	(0x9999, "MetaX Integrated Circuits (Shanghai) Co., Ltd."),
	(0x9D32, "Beijing Starblaze Technology Co., LTD"),
	(0x9D68, "Brite Semiconductor (Shanghai) Corporation, Ltd."),
	(0x1013, "Cirrus Logic, Inc."),
	(0x1014, "IBM"),
	(0x1018, "Unisys Corporation"),
	(0x1019, "Elitegroup Computer Systems Inc."),
	(0x101E, "American Megatrends Incorporated"),
	(0x101E, "AMI US Holdings, Inc."),
	(0x1021, "Oki Electric Industry Co., Ltd."),
	(0x1022, "Advanced Micro Devices, Inc."),
	(0x1024, "Beijing Dajia Internet Information Technology Co., Ltd."),
	(0x1028, "Dell Computer Corporation"),
	(0x102B, "Matrox Graphics Inc."),
	(0xA23B, "Silicon Integrated Systems"),
	(0x103C, "HP Inc."),
	(0x103C, "Hewlett Packard"),
	(0x1043, "Asustek Computer Inc."),
	(0x104A, "STMicroelectronics International NV"),
	(0x104C, "Texas Instruments"),
	(0x104D, "Sony Group Corporation"),
	(0x1054, "Hitachi, Ltd."),
	(0x1059, "Kontron"),
	(0x105A, "Promise Technology, Inc."),
	(0x105B, "Foxconn (Hon Hai)"),
	(0x106B, "Apple Computer"),
	(0x1071, "MiTAC International Corporation"),
	(0x1073, "Yamaha Corporation"),
	(0x107D, "Leadtek Research Inc."),
	(0x108E, "Oracle"),
	(0x1093, "National Instruments Corporation"),
	(0x1093, "National Instruments"),
	(0x1096, "Alacron"),
	(0x10A0, "Meidensha Corporation"),
	(0x10AC, "Honeywell Inc."),
	(0x10B0, "Gainward Technology Int'l Limited"),
	(0x10B2, "Raytheon Company"),
	(0x10BA, "Mitsubishi Electric Corporation"),
	(0x10C5, "Xerox Corporation"),
	(0x10CB, "Omron Corporation"),
	(0x10CF, "Fujitsu Limited"),
	(0x10D2, "Molex LLC"),
	(0x10D3, "Jabil Circuit Inc."),
	(0x10DB, "Rohm Co., Ltd."),
	(0x10DC, "CERN"),
	(0x10DE, "NVidia Corporation"),
	(0x10EC, "Realtek Semiconductor Corporation"),
	(0x10EE, "Xilinx, Inc."),
	(0x10FC, "I-O Data Device, Inc."),
	(0x1102, "Creative Technology Ltd"),
	(0x1106, "VIA Technologies, Inc."),
	(0x110A, "Siemens AG"),
	(0x1113, "Accton Technology Corporation"),
	(0x112B, "Heidelberger Druckmaschinen AG"),
	(0xABCD, "Vadatech Inc."),
	(0x1131, "NXP Semiconductors"),
	(0x1134, "Mercury Computer Systems, Inc."),
	(0x1135, "FUJIFILM Business Innovation Corp."),
	(0x1137, "Cisco Systems, Inc."),
	(0x1147, "Interface Corporation"),
	(0xAD00, "Alta Data Technologies"),
	(0xAD10, "New Wave Design and Verification, LLC"),
	(0x114F, "Digi International Inc."),
	(0x1154, "Buffalo Inc."),
	(0xAD5A, "ADVA Optical Networking SE"),
	(0x115C, "Photron Limited"),
	(0x1165, "Foresight Imaging LLC"),
	(0x1168, "Thine Electronics, Inc"),
	(0x1170, "Inventec Corporation"),
	(0x1179, "Toshiba Corporation"),
	(0x1180, "Ricoh Company, Ltd."),
	(0x1189, "Panasonic Corporation"),
	(0x1192, "Densan Co., Ltd."),
	(0x1195, "Ratoc Systems Inc."),
	(0x119A, "Mindshare, Inc."),
	(0x119D, "B.U.G. MORI SEIKI CO., LTD."),
	(0x119D, "DMG MORI B.U.G. CO., LTD."),
	(0x119F, "BULL SAS"),
	(0x11A1, "Hamamatsu Photonics K.K."),
	(0x11AC, "Canon, Inc."),
	(0x11BF, "Astrodesign, Inc."),
	(0x11C6, "SCREEN GRAPHIC SOLUTIONS CO., LTD."),
	(0x11C8, "Dolphin Interconnect Solutions AS"),
	(0x11CA, "IBEX Technology, Co. Ltd."),
	(0x11D4, "Analog Devices International"),
	(0x11D7, "Trenton Systems, Inc."),
	(0x11DB, "SEGA CORPORATION"),
	(0x11EC, "Teledyne Dalsa"),
	(0x11F8, "Microchip Technology"),
	(0x1204, "Lattice Semiconductor Corporation"),
	(0x1217, "BayHub Technology Inc"),
	(0x1221, "Contec Co., Ltd."),
	(0x1227, "Tech Source Inc."),
	(0x1227, "EIZO Rugged Solutions"),
	(0x1235, "SMART Modular Technologies"),
	(0x123C, "CENTURY SYSTEMS Co.,Ltd."),
	(0x123D, "Engineering Design Team, Inc."),
	(0x1244, "AVM Audiovisuelles Marketing und Computersysteme GmbH"),
	(0x1250, "Hitachi Solutions Technology, Ltd."),
	(0x1253, "Guzik Technical Enterprises"),
	(0x1259, "Allied Telesis Inc."),
	(0x125F, "Concurrent Technologies"),
	(0x1268, "Tektronix"),
	(0x1269, "Thales"),
	(0x126F, "Silicon Motion Inc."),
	(0x1270, "Olympus Corporation"),
	(0x1275, "NetApp, Inc."),
	(0x1281, "Yokogawa Electric Corporation"),
	(0x1283, "ITE Tech. Inc."),
	(0x1297, "Shuttle Inc"),
	(0x12A0, "Rockwell Automation Inc. (Allen-Bradley)"),
	(0x12A4, "NTT Electronics Corporation"),
	(0x01DE, "Oxide Computer Company"),
	(0x12AF, "TDK Corporation"),
	(0x12B7, "Cognex Corporation"),
	(0x12C4, "Connect Tech Inc."),
	(0x12D6, "Analogic Corporation"),
	(0x12D8, "Diodes Incorporated"),
	(0x12D8, "Pericom Semiconductor"),
	(0x12DB, "Annapolis Micro Systems, Inc."),
	(0x12E1, "Nintendo Co., Ltd."),
	(0xBDBD, "Blackmagic Design Pty Ltd"),
	(0x12FE, "esd electronics gmbh"),
	(0x1304, "Juniper Networks"),
	(0x130F, "Advanet, Inc."),
	(0x1313, "YASKAWA Electric Corporation"),
	(0x1316, "Teradyne, Inc."),
	(0x131F, "SIIG Inc."),
	(0x1322, "MIS Corporation"),
	(0x1344, "Micron Technology, Inc."),
	(0x1349, "Sumitomo Electric Industries, Ltd."),
	(0x135E, "Sealevel Systems, Inc."),
	(0x1360, "Meinberg Funkuhren GmbH & Co. KG"),
	(0x1363, "Phoenix Technologies"),
	(0x1367, "Hitachi Zosen Corporation"),
	(0x1369, "Digigram"),
	(0x136C, "CPI Technologies, Inc."),
	(0x1374, "Silicom, Ltd."),
	(0x137A, "Mark of the Unicorn, Inc."),
	(0x1380, "Sanritz Automation Co., Ltd."),
	(0x138B, "TOKYO KEIKI INC."),
	(0x13A1, "Kawasaki Heavy Industries, Ltd."),
	(0x13B5, "ARM Ltd."),
	(0x13B8, "Nokia Solutions and Networks Oy"),
	(0x13B9, "ELECOM CO LTD"),
	(0xC5EC, "Citadel Securities LLC"),
	(0x13CC, "Barco, Inc."),
	(0x13D6, "K.I. Technology Co., Ltd"),
	(0x13DE, "ABB AB"),
	(0x13E5, "Telesoft Technologies Ltd."),
	(0x13E6, "ARGOSY RESEARCH INC."),
	(0x13F6, "C-MEDIA ELECTRONICS INC."),
	(0x13FE, "Advantech Co., Ltd."),
	(0x1407, "Lava Computer MFG. Inc."),
	(0x140E, "GOEPEL electronic GmbH"),
	(0x1414, "Microsoft"),
	(0x1425, "Chelsio Communications"),
	(0x1428, "EDEC Linsey System Co., Ltd."),
	(0x1433, "Eltec Elektronik AG"),
	(0x1435, "RTD Embedded Technologies, Inc."),
	(0x1442, "Phoenix Contact Electronics GmbH"),
	(0xCABC, "Cambricon Technologies Corporation Limited"),
	(0x1447, "AIM GmbH"),
	(0x144A, "ADLINK Technology"),
	(0x144B, "Verint"),
	(0x144D, "Samsung Electronics Co., Ltd."),
	(0x1458, "Giga-Byte Technology Co., Ltd."),
	(0x1461, "AVerMedia Technologies, Inc."),
	(0x1462, "Micro-Star International Co., Ltd."),
	(0x1463, "Fast Corporation"),
	(0xCC53, "ScaleFlux Inc."),
	(0xCCDE, "Code Construct Pty Ltd"),
	(0xCCEC, "Curtiss-Wright Controls Embedded Computing"),
	(0x148A, "OPTO 22"),
	(0x148C, "Tul Corporation"),
	(0x1498, "TEWS Technologies GmbH"),
	(0xCDFA, "NextSilicon Ltd"),
	(0x14A0, "Softing AG"),
	(0x14A4, "Lite-On Technology Corporation"),
	(0x14A9, "Hivertec, Inc."),
	(0xCEBA, "KEBA AG"),
	(0x14C0, "Compal Electronics, Inc."),
	(0x14C3, "MediaTek Incorporation"),
	(0x14CD, "Universal Global Scientific Industrial Co., Ltd"),
	(0x14D2, "TITAN Electronics Inc."),
	(0x14D6, "Accusys Storage LTD."),
	(0xD063, "SolidRun Ltd"),
	(0x14E4, "Broadcom Limited"),
	(0x14EB, "Seiko Epson Corporation"),
	(0x14FF, "Twinhead International Corporation"),
	(0x150B, "Yamashita Systems Corp"),
	(0x1513, "TE Connectivity"),
	(0x1529, "ON Semiconductor"),
	(0x152D, "Quanta Computer Inc."),
	(0x152E, "Melec Inc."),
	(0x1543, "Skyworks Solutions, Inc."),
	(0x1546, "IOI Technology Corporation"),
	(0x1547, "Mitutoyo Corporation"),
	(0x1558, "Clevo Co."),
	(0x1569, "Palit Microsystems Ltd."),
	(0x156C, "VMagic Electronics GmbH"),
	(0x1570, "Teledyne LeCroy"),
	(0x1576, "Osprey Video"),
	(0x1590, "Hewlett Packard Enterprise"),
	(0x159C, "Stratus Technologies, Inc."),
	(0x15A5, "Toyota Technical Development Corporation"),
	(0x15AD, "Vmware, Inc."),
	(0x15B8, "ADDI-DATA Gmbh"),
	(0x15BB, "Portwell Inc"),
	(0x15BB, "Portwell, Inc."),
	(0x15BC, "Keysight Technologies"),
	(0x15BD, "DFI Inc."),
	(0x15CF, "Hilscher Gesellschaft fuer Systemautomation mbH"),
	(0x15D7, "Collins Aerospace"),
	(0x15D9, "Super Micro Computer Inc."),
	(0xDA7A, "Speedata Inc."),
	(0x15E0, "Blue Coat Systems"),
	(0x15E7, "GET Engineering Corporation"),
	(0x160C, "OMS Motion, Inc."),
	(0x160C, "Pro-Dex, Oregon Micro Systems"),
	(0x160D, "AAEON Electronics, Inc."),
	(0xDD01, "Digital Devices"),
	(0x1629, "Kongsberg Defence & Aerospace AS - Spacetec"),
	(0x162F, "ROHDE & SCHWARZ GmbH & Co. KG"),
	(0x163F, "Renishaw plc."),
	(0x1642, "Shenzhen Bitland Information Technology Co., Ltd"),
	(0xDEDA, "XIMEA"),
	(0x165C, "Gidel Ltd."),
	(0x1679, "Tokyo Electron Device Ltd."),
	(0x1683, "StepTechnica Co., Ltd."),
	(0x169A, "Otari, Inc."),
	(0x16C3, "Synopsys, Inc."),
	(0x16C8, "Octasic Inc."),
	(0x16CB, "Konica Minolta Holdings Inc."),
	(0x16CE, "Roland Corporation"),
	(0xE4BF, "EKF Elektronik GmbH"),
	(0x16E2, "Marvin Test Solutions, Inc."),
	(0x16EA, "Fuji Electric Co., Ltd."),
	(0x16F2, "Bosch Rexroth AG"),
	(0x1718, "Pixela Corporation"),
	(0x1735, "Aten International Co., Ltd."),
	(0x1738, "L3Harris Technologies, Inc."),
	(0x1739, "Interface Concept"),
	(0x174A, "Spirent Communications"),
	(0x174B, "PC Partner Limited"),
	(0x174F, "SAXA, Inc."),
	(0x175C, "AudioScience, Inc."),
	(0x1761, "Pickering Interfaces Ltd."),
	(0xEA50, "Emerson Automation Solutions"),
	(0x1771, "InnoVision Multimedia, Ltd."),
	(0x1775, "General Electric"),
	(0x1778, "For-A Company Limited"),
	(0xEACE, "Endace Technology Ltd."),
	(0x177C, "EBRAINS, INC."),
	(0x1784, "Lockheed Martin"),
	(0x1792, "Artiza Networks, Inc."),
	(0x1795, "OKB SAPR"),
	(0x1796, "Forschungszentrum Jülich GmbH"),
	(0x17A0, "Genesys Logic, Inc."),
	(0x17AA, "Lenovo"),
	(0xECAB, "GM Cruise LLC"),
	(0x17C0, "Wistron Corporation"),
	(0x17C3, "Protogate, Inc."),
	(0x17CB, "Qualcomm Incorporated"),
	(0x17CD, "Cadence Design Systems"),
	(0x17CE, "BCM Advanced Research"),
	(0x17D2, "SigBitz LLC"),
	(0x17D3, "Areca Technology Corporation"),
	(0x17E8, "Chrontel, Inc."),
	(0x17ED, "ARBOR Technology Corp"),
	(0x17F3, "RDC Semiconductor Co., Ltd."),
	(0xEFAB, "Enfabrica Corporation"),
	(0x17F9, "GemTek Technology Co., Ltd."),
	(0x1805, "Euresys s.a."),
	(0x1808, "nVent, Schroff GmbH"),
	(0x180C, "IEI Integration Corp."),
	(0x1817, "JAE"),
	(0xF111, "Framework Computer Inc."),
	(0xF117, "Rockport Networks Inc."),
	(0x181D, "eInfochips, Inc."),
	(0xF15E, "SiFive, Inc."),
	(0xF1D0, "AJA Video"),
	(0x1830, "Cohu, Inc."),
	(0x184B, "SYSTEC Corporation"),
	(0x184C, "Hirose Electric USA Inc."),
	(0x1850, "Advantest Corporation"),
	(0x1852, "Anritsu Corporation"),
	(0x1872, "A & D Company, Ltd."),
	(0x1880, "LOTES Co., Ltd"),
	(0x188B, "Faraday Technology Corporation"),
	(0x1893, "Kyocera Corporation"),
	(0x1895, "Flextronics International"),
	(0xF5F5, "F5 Networks, Inc."),
	(0x18B2, "K.K. Rocky"),
	(0x18B4, "Yamaichi Electronics"),
	(0x18D1, "ULVAC-PHI, Inc."),
	(0x18D4, "Celestica"),
	(0x18D7, "Sierra Wireless, Inc."),
	(0x18E4, "Acer Inc."),
	(0x18E6, "MPL AG"),
	(0x18EF, "Avery Design systems, Inc."),
	(0x18F1, "Spectrum Instrumentation GmbH"),
	(0x18F2, "Dai-Ichi Seiko Co., Ltd(I-PEX)"),
	(0x18F2, "I-PEX (Dai-ichi Seiko)"),
	(0x18F4, "Napatech AS"),
	(0x18F8, "Amphenol Corp."),
	(0x18FD, "Digital Media Professionals, Inc."),
	(0x18FE, "Opex Corporation"),
	(0x190E, "Fidus Systems Inc."),
	(0x1912, "Renesas Electronics Corporation"),
	(0x1916, "Macnica, Inc."),
	(0x191E, "SRISA"),
	(0x1923, "Sangoma Technologies Corporation"),
	(0x1933, "Nexcom International"),
	(0x193D, "New H3C Technologies Co., Ltd."),
	(0x194A, "Dap Holding B.V."),
	(0x194F, "Allion Labs, Inc."),
	(0x1954, "One Stop Systems, Inc."),
	(0x1960, "REJ Co., Ltd."),
	(0x1962, "U.S. Patent & Trademark Office"),
	(0xFDEF, "Fermionic Design Private Limited"),
	(0xFE19, "TenaFe Inc."),
	(0x1974, "STAR Electronics GmbH & Co. KG"),
	(0x1974, "Eberspächer Electronics GmbH & Co. KG"),
	(0x1977, "Etion Create (Pty) Ltd."),
	(0x197B, "JMicron Technology Corporation"),
	(0x197D, "Cap Co., Ltd."),
	(0x1987, "Phison Electronics Corporation"),
	(0x19A4, "Owl Cyber Defense Solutions LLC"),
	(0x19A6, "HDL Design House"),
	(0x19AA, "Rambus Inc."),
	(0x19BC, "Ueda Japan Radio Co., Ltd."),
	(0x19BF, "Unicom Engineering Inc"),
	(0x19CB, "Hartmann Electronic GmbH"),
	(0x19D4, "Quixant Plc"),
	(0x19D5, "Protech Systems"),
	(0x19D7, "Astek Corporation"),
	(0x19E2, "Vector Informatik GmbH"),
	(0x19E5, "Huawei Technologies Co., Ltd."),
	(0x19EB, "DAIHEN Corporation"),
	(0x19EC, "ANSYS, Inc."),
	(0x19EE, "Netronome"),
	(0x1A00, "Universal Audio, Inc."),
	(0x1A03, "ASPEED Technology Inc."),
	(0x1A05, "Delta Electronics, Inc."),
	(0x1A07, "Kvaser AB"),
	(0x1A0D, "SEAKR Engineering Inc."),
	(0x1A0E, "DekTec Digital Video B.V."),
	(0x1A11, "BitifEye Digital Test Solutions GmbH"),
	(0x1A12, "Taiwan Commate Computer"),
	(0x1A15, "Axell Corporation"),
	(0x1A1F, "Avago Technologies"),
	(0x1A25, "Ericsson AS"),
	(0x1A29, "Fortinet, Inc."),
	(0x1A2F, "congatec GmbH"),
	(0x1A3B, "AzureWave Technologies, Inc."),
	(0x1A3D, "Tritek Co., Ltd."),
	(0x1A3F, "KEL Corporation"),
	(0x1A43, "Chuo Electronics Co., Ltd."),
	(0x1A4C, "Amulet Hotkey Ltd."),
	(0x1A61, "Astron Technology Corp."),
	(0x1A6E, "International Game Technology"),
	(0x1A82, "Samtec"),
	(0x1A83, "Gopher Inc."),
	(0x1A83, "ARKUS Inc."),
	(0x1A8A, "Star Bridge, Inc."),
	(0x1A9D, "QSC Audio Products, LLC"),
	(0x1AA1, "Aristocrat Technologies Australia Pty Ltd."),
	(0x1AA2, "Media Links Co., LTD."),
	(0x1AA9, "Schweitzer Engineering Labs, Inc."),
	(0x1AAC, "IBASE Technology Inc."),
	(0x1AB8, "Parallels International GmbH"),
	(0x1ABB, "Key ASIC Berhad"),
	(0x1AC1, "Global Unichip Corp."),
	(0x1AC2, "Avalue Technology Inc."),
	(0x1ACD, "Airbus DS Electronics and Border Security GmbH"),
	(0x1ACD, "Hensoldt Sensors GmbH"),
	(0x1ACD, "Cassidian"),
	(0x1AE0, "Google, Inc."),
	(0x1AE8, "Basler AG"),
	(0x1AF8, "Parade Technologies, Inc."),
	(0x1B00, "Montage Technology Co., Ltd."),
	(0x1B05, "Benchmark Electronics, Inc."),
	(0x1B07, "NEXTCHIP Co,Ltd"),
	(0x1B08, "Avnet Embedded GmbH"),
	(0x1B08, "MSC Vertriebs GmbH"),
	(0x1B0A, "Pegatron Corporation"),
	(0x1B0C, "Northrop Grumman Corp., Electronic Systems"),
	(0x1B12, "Analogix Semiconductor"),
	(0x1B17, "WinSystems, Inc."),
	(0x1B26, "INVEA-TECH a.s."),
	(0x1B2A, "Keyence Corporation"),
	(0x1B2E, "Riverbed Technology, Inc."),
	(0x1B37, "SP Devices"),
	(0x1B37, "Teledyne SP Devices"),
	(0x1B42, "Ceremorphic, Inc"),
	(0x1B45, "StarTech.com Ltd."),
	(0x1B49, "ALLDIS Computersystem GmbH"),
	(0x1B4C, "Galaxy Microsystems Ltd."),
	(0x1B4E, "Nations Technologies Inc."),
	(0x1B53, "iD corporation"),
	(0x1B59, "Achronix Semiconductor"),
	(0x1B5E, "Star-Dundee Ltd."),
	(0x1B66, "Deltatec"),
	(0x1B6B, "Teledyne Digital Imaging dba Teledyne Photometrics dba Teledyne QImaging"),
	(0x1B6F, "Etron Technology, Inc."),
	(0x1B76, "AIC Inc."),
	(0x1B7B, "Multisuns Corporation"),
	(0x1B83, "Viasat Inc."),
	(0x1B86, "Saab AB"),
	(0x1B8F, "Nanoteq (Pty) Ltd"),
	(0x1B95, "Green Hills Software"),
	(0x1B96, "Western Digital Technologies, Inc."),
	(0x1B98, "E.E.P.D. GmbH"),
	(0x1B9F, "BAE Systems"),
	(0x1BAA, "QNAP Systems, Inc."),
	(0x1BAD, "REFLEX CES"),
	(0x1BB1, "Seagate Technology LLC"),
	(0x1BB2, "Nikon Corporation"),
	(0x1BBA, "KLA-Tencor"),
	(0x1BC0, "InnoDisk Corporation"),
	(0x1BC1, "EXFO Inc."),
	(0x1BC8, "TokushuDenshiKairo Inc."),
	(0x1BC9, "Sonifex Ltd"),
	(0x1BCA, "Star Communications, Inc."),
	(0x1BCD, "Apacer Technology Inc."),
	(0x1BCE, "Silex Technology, Inc."),
	(0x1BCF, "NEC"),
	(0x1BD0, "Astronics Corporation"),
	(0x1BD4, "Inspur Electronic Information Industry Co., Ltd."),
	(0x1BD5, "The FreeBSD Foundation"),
	(0x1BD7, "Granite River Labs Inc."),
	(0x1BDC, "Intrado Inc."),
	(0x1BDD, "Atrust Computer Corp."),
	(0x1BDF, "LUXSHARE-ICT, Inc."),
	(0x1BE9, "The MathWorks, Inc."),
	(0x1BEB, "SignalCore, Inc."),
	(0x1BEC, "SECO S.P.A."),
	(0x1BEE, "IXXAT Automation GmbH"),
	(0x1BF5, "Greenliant"),
	(0x1BFA, "Daiichi Jitsugyo Viswill Co., Ltd"),
	(0x1BFB, "Analog Bits"),
	(0x1BFC, "duagon AG"),
	(0x1C04, "Dexon Systems Ltd"),
	(0x1C05, "Blackberry QNX"),
	(0x1C07, "HCL Technologies Ltd"),
	(0x1C0B, "Alazar Technologies, Inc."),
	(0x1C18, "ASSET InterTech, Inc."),
	(0x1C1A, "UNH InterOperability Laboratory"),
	(0x1C1A, "UNH InterOperability Laboratory (UNH-IOL)"),
	(0x1C1B, "Netlist, Inc."),
	(0x1C24, "Elma Bustronic Corp."),
	(0x1C2A, "Acromag, Inc"),
	(0x1C2E, "Schneider Electric Japan Holdings Ltd."),
	(0x1C2F, "Beckhoff Automation GmbH & Co. KG"),
	(0x1C33, "Daktronics, Inc."),
	(0x1C33, "Daktronics"),
	(0x1C37, "Shikino High-Tech Co., Ltd"),
	(0x1C46, "Cosmotechs Co., Ltd."),
	(0x1C4E, "Techway"),
	(0x1C4F, "Bruker Corporation"),
	(0x7248, "BizLink Technology, Inc."),
	(0x1C55, "Hexagon Metrology S.P.A."),
	(0x1C5B, "XJTAG Ltd."),
	(0x1C5C, "SK Hynix"),
	(0x1C5D, "Telit Communications SPA"),
	(0x1C5E, "GopherTec Inc."),
	(0x1C5F, "Beijing Memblaze Technology Co. Ltd."),
	(0x1C64, "TRS-RenTelco"),
	(0x1C65, "Jump Trading Group"),
	(0x1C67, "PreSonus Audio Electronics Inc."),
	(0x1C69, "Comtel Electronics GmbH"),
	(0x1C6C, "Wibtek Electronics Co., Ltd"),
	(0x1C6F, "Bios Corporation"),
	(0x1C71, "Shimadzu Corporation"),
	(0x1C72, "ProDesign Electronic GmbH"),
	(0x1C75, "Bellwether Electronic Corp."),
	(0x1C78, "Bechtel Marine Propulsion Corporation"),
	(0x1C7A, "Other World Computing"),
	(0x1C7E, "TTTech Computertechnik AG"),
	(0x1C7F, "Elektrobit Austria GmbH"),
	(0x1C82, "HUBER+SUHNER Inc"),
	(0x1C85, "ABLIC Inc."),
	(0x1C94, "Aces Electronics Co., Ltd."),
	(0x1C96, "Carina System Co., Ltd."),
	(0x1C9D, "Illumina"),
	(0x1CA0, "MEMORIGHT"),
	(0x1CA1, "Sync-n-Scale, LLC"),
	(0x1CAB, "Lynx Software Technologies, Inc."),
	(0x1CAD, "EXTOLL GmbH"),
	(0x1CB0, "Shannon Systems"),
	(0x1CB4, "SerialTek"),
	(0x1CB5, "Focusrite Audio Engineering Ltd"),
	(0x1CB8, "Dawning Information Industry Co., Ltd."),
	(0x1CBD, "Novachips Co., Ltd"),
	(0x1CBF, "Ross Video"),
	(0x1CC1, "ADATA Technology Co., Ltd."),
	(0x1CC2, "Unigen Corporation"),
	(0x1CC3, "Sanmina"),
	(0x1CC4, "Shenzhen Unionmemory Information System Limited"),
	(0x1CCE, "Wilder Technologies"),
	(0x1CDA, "ADTEC Corporation"),
	(0x1CDD, "Secunet Security Networks AG"),
	(0x1CDF, "SmartDV North America, LLC"),
	(0x1CEB, "Taiwan Pulse Motion Co., Ltd."),
	(0x1CEE, "Chant Sincere Co., Ltd."),
	(0x1CF2, "ZTE Corporation"),
	(0x1CF6, "Aetina Corporation"),
	(0x1CF7, "Subspace Dynamics LLC"),
	(0x1CF8, "Fibocom Wireless Inc."),
	(0x1CFA, "Corsair Memory, Inc"),
	(0x1CFB, "Innotech Corporation"),
	(0x1CFC, "Naltec, Inc."),
	(0x1D00, "Pure Storage, Inc."),
	(0x1D04, "Allied Vision Technologies"),
	(0x1D05, "TONGFANG HONGKONG LIMITED"),
	(0x1D08, "Shen Zhen Deren Electronic Co., LTD."),
	(0x1D0F, "Amazon"),
	(0x1D12, "JESS-LINK PRODUCTS CO., LTD."),
	(0x1D13, "Prodigy Technovations Private Limited"),
	(0x1D14, "Lintes Technology Co., Ltd."),
	(0x1D17, "Shanghai Zhaoxin Semiconductor Co., Ltd."),
	(0x1D18, "RME GmbH"),
	(0x1D19, "VAIO Corporation"),
	(0x1D1D, "CNEX LABS Inc."),
	(0x1D1E, "Solid State System"),
	(0x1D26, "KALRAY"),
	(0x1D27, "M31 Technology Corporation"),
	(0x1D28, "Aava Mobile Oy"),
	(0x1D29, "Hagiwara Solutions Co., Ltd."),
	(0x1D2A, "KAYA Instruments Ltd"),
	(0x1D2D, "Good Way Technology Co., Ltd."),
	(0x1D32, "Genesis Co.,Ltd"),
	(0x1D33, "Prodrive Technologies"),
	(0x1D36, "Airbus Defence and Space GmbH"),
	(0x1D38, "Colorado Engineering Inc."),
	(0x1D39, "Baikal Electronics, JSC"),
	(0x1D45, "Top Victory Investments Limited"),
	(0x1D47, "Ciena Corporation"),
	(0x1D4B, "Elektrosfera LTD."),
	(0x1D4C, "Diamanti, Inc."),
	(0x1D4C, "Datawise Systems, Inc."),
	(0x1D4D, "Integrated Design Tools, Inc."),
	(0x1D58, "Atech Flash Technology, Inc"),
	(0x1D61, "Technobox, Inc."),
	(0x1D64, "Quarch Technology Ltd"),
	(0x1D67, "Alltop Technology Co., Ltd"),
	(0x1D6B, "ZAO Kraftway Corporation PLC"),
	(0x1D72, "Xiaomi Communications Co., Ltd."),
	(0x1D78, "Dera co., Ltd."),
	(0x1D79, "Transcend Information, Inc."),
	(0x1D7C, "Aerotech Inc"),
	(0x1D7D, "Viavi Solutions"),
	(0x1D7F, "Plugable"),
	(0x1D80, "COTS Technology"),
	(0x1D82, "NETINT Technologies Inc."),
	(0x1D83, "Uniconn Corp."),
	(0x1D84, "b-plus technologies GmbH"),
	(0x1D85, "Neosem Holdings Inc"),
	(0x1D86, "Evertz Microsystems Ltd."),
	(0x1D87, "Rockchip Electronics Co., Ltd."),
	(0x1D88, "Telechips Inc."),
	(0x1D89, "YEESTOR Microelectronics Co., Ltd"),
	(0x1D8C, "FASTWEL Group Co. Ltd"),
	(0x1D8D, "Fiberhome Telecommunication Technologies"),
	(0x1D8E, "MACOM Technology Solutions Inc."),
	(0x1D8F, "ENYX"),
	(0x1D92, "Abaco Systems Inc."),
	(0x1D93, "YADRO"),
	(0x1D94, "Chengdu Higon Integrated Circuit Design Co., Ltd."),
	(0x1D95, "Graphcore Ltd"),
	(0x1D97, "Shenzhen Longsys Electronics Co., Ltd."),
	(0x1D9B, "Facebook"),
	(0x1DA0, "3M Company"),
	(0x1DA1, "Teko Telecom S.r.l. a Socio Unico"),
	(0x1DA2, "Sapphire Technology Limited"),
	(0x1DA5, "UTran Technology Inc."),
	(0x1DA8, "Corigine Inc."),
	(0x1DAC, "SparkLAN Communications, Inc."),
	(0x1DAE, "Vectology,Inc."),
	(0x1DAF, "MIT Lincoln Laboratory"),
	(0x1DB2, "ATP Electronics, Inc."),
	(0x1DB3, "Unisoc (Shanghai) Technologies Co., Ltd."),
	(0x1DB4, "Arteris Inc."),
	(0x1DBB, "NGD Systems, Inc."),
	(0x1DBD, "Logic Fruit Technologies Pvt Ltd"),
	(0x1DBE, "INNOGRIT CORPORATION"),
	(0x1DC2, "Alco Digital Devices Limited"),
	(0x1DC5, "FADU Inc."),
	(0x1DC6, "Fox Crypto B.V."),
	(0x1DC7, "SSI Computer Corp"),
	(0x1DC9, "UniTest"),
	(0x1DCA, "Marvell Semiconductor, Inc."),
	(0x1DCD, "Liqid Inc"),
	(0x1DCF, "Beijing Sinead Technology Co., Ltd."),
	(0x1DD0, "McDowell Signal Processing, LLC"),
	(0x1DD3, "Sage Microelectronics Corp.(*Suspended)"),
	(0x1DD4, "Swissbit AG"),
	(0x1DD6, "ECRIN SYSTEMS"),
	(0x1DD7, "AVAL DATA Corporation"),
	(0x1DD8, "Pensando Systems"),
	(0x1DDB, "Parraid, LLC"),
	(0x1DDC, "Carlisle Interconnect Technologies"),
	(0x1DDE, "Valens Semiconductor Ltd."),
	(0x1DDF, "RTO Systems LTD"),
	(0x1DE0, "Groq, Inc."),
	(0x1DE2, "Action Star Technology Co., Ltd."),
	(0x1DE5, "Eideticom"),
	(0x1DE6, "Communication Automation Corporation"),
	(0x1DE8, "Acqiris SA"),
	(0x1DED, "Alibaba (China) Co., Ltd."),
	(0x1DEE, "Biwin Storage Technology Co., Ltd."),
	(0x1DEF, "Ampere Computing, LLC"),
	(0x1DF3, "Ethernity Networks Ltd"),
	(0x1DF5, "ShenZhen TIGO Semiconductor Co., Ltd."),
	(0x1DF7, "opencpi.org"),
	(0x1DF8, "V&G Information System Co.,Ltd"),
	(0x1DF9, "Simula Technology Inc."),
	(0x1DFA, "Astera Labs, Inc."),
	(0x1DFC, "LTD NTCOM"),
	(0x1DFD, "CDSG"),
	(0x1E01, "Synaptics, Inc."),
	(0x1E02, "NSITEXE, Inc."),
	(0x1E03, "OnLogic, Inc."),
	(0x1E05, "Exicon Co., Ltd."),
	(0x1E09, "Novatek Microelectronics Corporation"),
	(0x1E0A, "Esperanto Technologies, Inc"),
	(0x1E0B, "Shenzhen Decenta Technology Co.,LTD"),
	(0x1E0C, "Axiomtek Co., Ltd."),
	(0x1E0D, "SambaNova Systems, Inc."),
	(0x1E0F, "Kioxia Corporation"),
	(0x1E10, "eSOL Co.,Ltd."),
	(0x1E12, "Introspect Technology"),
	(0x1E14, "Silicon Creations, LLC"),
	(0x1E15, "Wieson Technologies Co., LTD."),
	(0x1E16, "BOXX Technologies, LLC"),
	(0x1E17, "Arnold & Richter Cine Technik GmbH & Co. Betriebs KG"),
	(0x1E1B, "Firm INFORMTEST Ltd."),
	(0x1E23, "Credo Semiconductor, Inc."),
	(0x1E27, "Shanghai Denglin Technologies Co., Ltd"),
	(0x1E2E, "Mercedes-Benz R&D North America, Inc."),
	(0x1E31, "SORD Corporation"),
	(0x1E32, "Tuxera Inc."),
	(0x1E33, "Delkin Devices"),
	(0x1E34, "Qrypt, Inc."),
	(0x1E36, "Shanghai Enflame Technology Co. Ltd"),
	(0x1E39, "MEDION AG"),
	(0x1E3A, "Cactus Technologies, Limited"),
	(0x1E3B, "DapuStor Corporation"),
	(0x1E3D, "Burlywood, Inc"),
	(0x1E3E, "Shanghai Iluvatar CoreX Semiconductor Co., Ltd."),
	(0x1E3F, "Linaro Limited"),
	(0x1E42, "ART Beijing Science and Technology Development Co., Ltd."),
	(0x1E43, "MaxLinear Inc"),
	(0x1E44, "Valve Software"),
	(0x1E45, "ESSENCORE Limited"),
	(0x1E46, "Varjo Technologies Oy"),
	(0x1E47, "SZ DJI Technology Co., Ltd."),
	(0x1E48, "Continental Autonomous Mobility Germany GmbH"),
	(0x1E49, "Yangtze Memory Technologies Co.,Ltd"),
	(0x1E4A, "2CRSI SA"),
	(0x1E4B, "Maxio Technology (Hangzhou) Ltd."),
	(0x1E4C, "GSI Technology"),
	(0x1E50, "IP3 Tech (HK) Limited"),
	(0x1E51, "UAB Neurotechnologijos"),
	(0x1E52, "Tenstorrent Inc"),
	(0x1E53, "Mythic - AI"),
	(0x1E55, "ETC"),
	(0x1E58, "Kinara Inc."),
	(0x1E59, "Oxford Nanopore Technologies plc"),
	(0x1E5C, "Alphawave IP"),
	(0x1E5D, "ASR Microelectronics Co., Ltd."),
	(0x1E5E, "Emergent Vision Technologies Inc"),
	(0x1E60, "HAILO Technologies LTD."),
	(0x1E63, "Shenzhen iNet Mobile Internet Technology Co.,Ltd"),
	(0x1E67, "Untether AI Corporation"),
	(0x1E68, "Jiangsu Xinsheng Intelligent Technology Co., Ltd."),
	(0x1E6A, "IRISO Electronics Co., Ltd"),
	(0x1E6B, "Axiado Corporation"),
	(0x1E6C, "Xsight Labs Ltd"),
	(0x1E6F, "Kandou Bus S.A."),
	(0x1E70, "Primesoc Technologies"),
	(0x1E72, "Zoox Inc"),
	(0x1E73, "NeuroBlade"),
	(0x1E75, "Wind River Systems, Inc."),
	(0x1E76, "Zhejiang Zhaolong Interconnect Technology Co., Ltd"),
	(0x1E78, "Beijing SenseTime Technology Development Co.,Ltd"),
	(0x1E7C, "Brainchip, Inc."),
	(0x1E7D, "Daichu Technologies Co.,Ltd."),
	(0x1E7E, "PLIOPS LTD."),
	(0x1E7F, "Jiangsu Huacun Electronic Technology Co., Ltd."),
	(0x1E81, "Ramaxel Technology (Shenzhen) Limited"),
	(0x1E82, "Dongguan Yizhao Electronic Co.,Ltd."),
	(0x1E83, "Huaqin Technology Co.Ltd"),
	(0x1E85, "Heitec AG"),
	(0x1E86, "Wintec Industries, Inc."),
	(0x1E87, "Shenzhen Shinning Electronic Co.,Ltd."),
	(0x1E8A, "Cornami, Inc."),
	(0x1E92, "Raymax Technology Ltd."),
	(0x1E93, "Beijing Bytedance Network Technology Co., Ltd."),
	(0x1E96, "Drut Technologies Inc."),
	(0x1E97, "Caswell Inc."),
	(0x1E99, "INTEGRATED SERVICE TECHNOLOGY Inc."),
	(0x1E9A, "Neoconix"),
	(0x1E9C, "Adnacom Inc."),
	(0x1E9D, "VersaLogic Corporation"),
	(0x1E9F, "Lynxi Technologies Ltd., Co."),
	(0x1EA0, "Tencent Technology (Shenzhen) Company Limited"),
	(0x1EA1, "Sichuan Huafeng Technology Co., Ltd."),
	(0x1EA2, "Cyber Cogs"),
	(0x1EA3, "Expedera, Inc"),
	(0x1EA4, "Newtech Co., Ltd."),
	(0x1EA5, "Chief Land Electronic Co., Ltd."),
	(0x1EA7, "IntelliProp Inc."),
	(0x1EA8, "Winintec"),
	(0x1EAA, "NTP Technology AS"),
	(0x1EAB, "Hefei DATANG Storage Technology Co.,LTD."),
	(0x1EAC, "Quectel Wireless Solutions Co., Ltd."),
	(0x1EAE, "XFX Limited"),
	(0x1EAF, "Palo Alto Networks"),
	(0x1EB0, "SHENZHEN ELECTRICAL APPLIANCES CO"),
	(0x1EB3, "Shenzhen Goodtimes Technology Co.,Ltd"),
	(0x1EB6, "Wuxi Stars Microsystem Technology Co., Ltd"),
	(0x1EB9, "Senscomm Semiconductor Co., Ltd."),
	(0x1EBB, "nCipher Security Ltd"),
	(0x1EBC, "Sabrent"),
	(0x1EBD, "EMERGETECH Company Ltd."),
	(0x1EC1, "Wiwynn Corporation"),
	(0x1EC2, "eTopus Technology Inc."),
	(0x1EC4, "Picocom Technology Limited"),
	(0x1EC6, "Vastai Technologies (Shanghai) Inc"),
	(0x1EC8, "Innosilicon Technology Ltd"),
	(0x1EC9, "Wingtech Group(HongKong)Limited"),
	(0x1ECA, "Lightmatter"),
	(0x1ECD, "Aquarius Production Company"),
	(0x1ECE, "EdgeQ, Inc."),
	(0x1ECF, "Base2 Engineering, LLC"),
	(0x1ED0, "Hosin Global Electronics Co., LTD."),
	(0x1ED2, "FuriosaAI, Inc."),
	(0x1ED3, "SHENZHEN YINGJIAXUN INDUSTRY CO., LTD"),
	(0x1ED4, "Shandong Exponent Semiconductor Co.,Ltd"),
	(0x1ED5, "Moore Threads Technology Co.,Ltd"),
	(0x1ED6, "Tanzanite Silicon Solutions, Inc."),
	(0x1ED7, "Sonic Star Global Limited Taiwan Branch"),
	(0x1ED8, "Digiteq Automotive s.r.o."),
	(0x1ED9, "Myrtle.ai"),
	(0x1EDA, "infodas GmbH"),
	(0x1EDB, "Anlogic Infotech Co., Ltd"),
	(0x1EDC, "InPsytech, Inc."),
	(0x1EDE, "DreamBig Semiconductor Inc"),
	(0x1EE0, "Shanghai Biren Technology Co., Ltd"),
	(0x1EE1, "Suzhou Kuhan Information technologies"),
	(0x1EE2, "plc2 Design GmbH"),
	(0x1EE4, "petaIO Corp"),
	(0x1EE5, "ThinkForce Electronic Technology Co., Ltd."),
	(0x1EE6, "Clientron Corp."),
	(0x1EE7, "Honor Device Co., Ltd."),
	(0x1EE8, "Shenzhen BXC Science and Technology Co.,Ltd."),
	(0x1EE9, "SUSE LLC"),
	(0x1EEB, "Kaimai Tech Ltd."),
	(0x1EEC, "Jiangsu Viscore Technologies Co.,Ltd"),
	(0x1EED, "Xiangdixian Computing Technology (Chongqing) Limited Company"),
	(0x1EEE, "Tracewell Systems, Inc."),
	(0x1EF0, "Ayar Labs"),
	(0x1EF1, "Black Sesame Technologies Co., Ltd."),
	(0x1EF2, "Smart IOPS, Inc."),
	(0x1EF4, "CHINA AVIATION OPTICAL-ELECTRICAL PRECISION ELECTRONIC SHENZHEN CO.,LTD"),
	(0x1EF5, "Winmate Inc."),
	(0x1EF6, "GrAI Matter Labs"),
	(0x1EF7, "Shenzhen Gunnir Technology Development Co., Ltd"),
	(0x1EF8, "APTIV"),
	(0x1EF9, "Zeku Technology (Shanghai) Corp., Ltd."),
	(0x1EFA, "Pacific Light & Hologram, Inc"),
	(0x1EFB, "Flexxon Pte Ltd"),
	(0x1EFD, "Rivos Inc"),
	(0x1EFE, "Peng Yu Trigold Limited"),
	(0x1EFF, "Rebellions Inc."),
	(0x1F00, "Enercon Technologies"),
	(0x1F02, "Beijing Dayu Technology Co.,Ltd"),
	(0x1F03, "Shenzhen Shichuangyi Electronics Co., Ltd"),
	(0x1F04, "iPasslabs Technology Co. Ltd."),
	(0x1F05, "WLCO(ShenZhen) Co.,Ltd."),
	(0x1F06, "SiMa.ai"),
	(0x1F07, "Mitsui Chemicals America, Inc."),
	(0x1F08, "Akrostar Technology Co., Ltd."),
	(0x1F0A, "Motorcomm Electronic Technology Co.,Ltd"),
	(0x1F0D, "DeGirum Corporation"),
	(0x1F0E, "Accipiter Systems, Inc."),
	(0x1F0F, "Nebula Matrix"),
	(0x1F13, "Listan GmbH"),
	(0x1F15, "Wolley (Taiwan) Ltd."),
	(0x1F16, "Xconn Technologies Holdings, Inc."),
	(0x1F17, "Zettastone Technology (wuhan) Co.,Ltd"),
	(0x1F18, "C-Payne PCB Design"),
	(0x1F19, "Wuxi High Information Security Technology Co. ,Ltd."),
	(0x1F1B, "42dot, Inc."),
	(0x1F1C, "SOPHGO Technologies Ltd."),
	(0x1F1D, "Initio (HK) Corporation Limited"),
	(0x1F1E, "CARIAD SE"),
	(0x1F1F, "Ranovus Inc."),
	(0x1F20, "Channel Well Technology Co., Ltd."),
	(0x1F21, "Delta Solutions LLC"),
	(0x1F22, "M SQUARE Ltd. Shanghai"),
	(0x1F23, "EVOC Intelligent Technology Co. Ltd."),
	(0x1F24, "xFusion Digital Technologies Co., Limited"),
	(0x1F25, "Nanjing Ruixinview Technology Co., Ltd"),
	(0x1F26, "SEMIFIVE, INC."),
	(0x1F27, "Beijing SoundPlus Technology Co. Ltd"),
	(0x1F28, "HisunTest Technologies (Beijing) Co., Ltd"),
	(0x1F29, "Square Route Co., Ltd."),
	(0x1F2A, "Argo AI, LLC"),
	(0x1F2B, "Wise Security Technology (Guangzhou) Co., Ltd"),
	(0x1F2D, "Elastics.cloud"),
	(0x1F2E, "AzurEngine Technologies Zhuhai"),
	(0x1F2F, "China Mobile (Hangzhou) Information Technology Co.Ltd."),
	(0x1F30, "Edelweiss, LLC"),
	(0x1F31, "Nextorage Corporation"),
	(0x1F32, "Wuhan YuXin Semiconductor Co., Ltd."),
	(0x1F33, "Purplelec Inc.Co.,Ltd"),
	(0x1F34, "Aviva Links"),
	(0x1F35, "Amlogic (CA) Co., Inc."),
	(0x1F36, "Moffett AI Technology Shenzhen Co., Ltd"),
	(0x1F37, "Hongkong Likfo (China) Business LTD"),
	(0x1F38, "Wisewave (Zhuhai) Technology Co., Ltd"),
	(0x1F39, "Silicon Innovation Technologies Co., Ltd."),
	(0x1F3A, "Powerleader Computer System Co., Ltd."),
	(0x1F3B, "Shunyao CAD (Shanghai) CO.,Ltd"),
	(0x1F3C, "Avant Technology"),
	(0x1F3D, "nLIGHT Inc."),
	(0x1F3F, "Shenzhen 3SNIC information technology company Limited"),
	(0x1F40, "Netac Technology Co.,Ltd"),
	(0x1F41, "AIO Core Co., Ltd."),
	(0x1F42, "EGK ELECTRONICS TECHNOLOGY LIMITED"),
	(0x1F43, "Ethernovia Inc."),
	(0x1F44, "VVDN Technologies. Private Limited"),
	(0x1F45, "Signal Easy Technologies Co., Ltd."),
	(0x1F46, "Shenzhen Chrent Technology Corp."),
	(0x1F47, "YUSUR Technology Co., Ltd."),
	(0x1F48, "Wistron NeWeb Corp."),
	(0x1F49, "NeuReality LTD"),
	(0x1F4A, "Shenzhen Corerain Technologies. Co. Ltd."),
	(0x1F4B, "Axera Semiconductor (Shanghai) Co., Ltd"),
	(0x1F4C, "Shenzhen Meigao Electronic Equipment Co.,Ltd"),
	(0x1F4D, "NIO Auto Co. Ltd."),
	(0x1F4E, "Shenzhen Konkr Technology Co., Ltd"),
	(0x1F4F, "Shanghai DaoCloud Network Technology Co,. Ltd"),
	(0x1F50, "LeRain Technology Co., Ltd"),
	(0x1F51, "CloudNine Information Technologies Co. Ltd"),
	(0x1F52, "MangoBoost Inc."),
	(0x1F53, "Shenzhen Jaguar Microsystems Co.,Ltd."),
	(0x1F54, "Teledyne FLIR"),
	(0x1F55, "Shenzhen MADIGI Electronic Technology Co.,Ltd"),
	(0x1F56, "SAPEON Inc."),
	(0x1F57, "Teletrx Co."),
	(0x1F58, "Wild River Technologies LLC"),
	(0x1F59, "Lucid Vision Labs, Inc."),
	(0x1F5B, "Roscoe Software LLC"),
	(0x1F5C, "TECNO MOBILE LIMITED"),
	(0x1F5D, "Shanghai UniVista Industrial Software Group Co., Ltd."),
	(0x1F5E, "Optos plc"),
	(0x1F5F, "DENKEI TRADING (SHANGHAI) CO.,LTD"),
	(0x1F60, "ACCELECOM LTD."),
	(0x1F61, "TuSimple"),
	(0x1F62, "Rosenberger Hochfrequenztechnik GmbH & Co.KG"),
	(0x1F63, "Tessolve Semiconductor Pvt Ltd"),
	(0x1F65, "Wuhan Lixi Intelligent Manufacturing Co., Ltd."),
	(0x1F66, "Shenzhen Huahong Intelligence Co,.Ltd."),
	(0x1F67, "Shanghai Yunsilicon Technology Co,. Ltd."),
	(0x1F69, "Shenzhen Haocheng Electronic Technology Co., Ltd"),
	(0x1F6A, "Ford Motor Company"),
	(0x1F6B, "Nanjing Houmo Technology Co.,Ltd."),
	(0x1F6C, "CIX Technology (Shanghai) Co., Ltd"),
	(0x1F6D, "Allwinner Technology Co., Ltd."),
	(0x1F6E, "Technolution B.V."),
	(0x1F6F, "Huaxia Smart Chip (Beijing) Technology Co., LTD"),
	(0x1F70, "Qualitas Semiconductor Co., Ltd."),
	(0x1F72, "Jane Street Group, LLC"),
	(0x1F73, "Shenzhen Quanxing Tech Co., Ltd"),
	(0x1F74, "Leica Camera AG"),
	(0x1F75, "Shenzhen One-Netbook Project Technology Co., Ltd"),
	(0x1F76, "SiEngine Technology Co Ltd"),
	(0x1F77, "Vast Data LTD"),
	(0x1F78, "Suvaca Technologies Private Limited"),
	(0x1F79, "Fraunhofer Institute for Industrial Mathematics (ITWM)"),
	(0x1F7A, "Efinix, Inc."),
	(0x1F7B, "CELESTIAL AI INC"),
	(0x1F7C, "Hong Kong Applied Science and Technology Research Institute (ASTRI)"),
	(0x1F7D, "QBit Semiconductor LTD."),
	(0x1F7E, "WILK ELEKTRONIK S.A."),
	(0x1F7F, "XEPIC Corporation Limited"),
	(0x1F80, "Shenzhen Tong Tai Yi information Technology Co.,Ltd"),
	(0x1F81, "CONNPRO ind."),
	(0x1F82, "d-Matrix Corporation"),
	(0x1F99, "Shenzhen Techwinsemi Technology Company Limited"),
	(0x1FAA, "Hexaflake (Shanghai) Information Technology Co., Ltd."),
	(0x1FAB, "UniFabriX Ltd."),
	(0x1FCB, "PerkinElmer"),
	(0x1FCB, "Varex Imaging Deutschland AG"),
	(0x1FCD, "Hitachi High-Tech Corporation"),
	(0x1FD4, "Sunix Co., Ltd."),
	(0x1FD9, "Neuchips Inc."),
	(0x2021, "Intelligent Memory Limited"),
	(0x21B4, "Hunan Goke Microelectronics Co., Ltd."),
	(0x22A2, "RIGOL TECHNOLOGIES CO., LTD."),
	(0x22B8, "Flex Logix Technologies, Inc."),
	(0x22C2, "Gowin Semiconductor Corporation"),
	(0x22DB, "Missing Link Electronics, Inc."),
	(0x2337, "Macronix International Co., Ltd."),
	(0x23E2, "streamcomputing"),
	(0x2646, "Kingston Technology Company ")
];