[package]
name        = "sys-ctrl"
version     = "0.1.0"
authors     = ["Tobias Pfeiffer <tobias@tobiaspfeiffer.net>"]
edition     = "2018"
publish     = false
#repository  = "https://gitlab.com/TobiP64/os"
license     = "MIT"
description = "System Control application for the OS"